### ISSUE TITLE
Create an own GitHub organization for word clocks?

### ISSUE THREAD

**Issue by tali** [tali/Wortuhr#6]
Es gibt verschiedene Wortuhr Projekte (z.B. von @Flo455, @dbambus), die einigermaßen unabhängig nebeneinander existieren.
Ich würde gerne eine GitHub Organisation mit einem zentralen Repository anlegen, um den Code zusammen zu führen und die Weiterentwicklung leichter bündeln zu können.
`github.com/Wortuhr` wäre ein guter Name, ist aber schon von @Wortuhr belegt.

@Wortuhr: würde es Dir etwas ausmachen für Deine privaten Projekte einen neuen GitHub Account zu verwenden und `Wortuhr` in eine Organisation zu verwandeln? (Klick auf Deinen Avatar -> Settings -> Organizations)

**Comment by dbambus** [comment]
Das wäre wirklich eine große Hilfe :-)

**Comment by Flo455** [comment]
Wär ich auch dabei, den ursprünglichen Master (von Eisbaeeer) in dem reingearbeitet wurde gibt’s leider nicht mehr, weis aber auch nicht wieso der gelöscht wurde.

**Comment by Wortuhr** [comment]
Hallo Martin
wenn ich das in eine Organisation umwandle, wer alles kann dann davon
profitieren? Zugreifen, hochladen? Ich verstehe GitHub noch nicht so ganz
und bin zur Zeit am Bastel an einer Wortuhr.
Danke für deine Antwort
Gruss Markus

Am Mo., 4. Jan. 2021 um 18:40 Uhr schrieb Flo455 <notifications@github.com>:

**Comment by tali** [comment]
Hallo Markus,

schön dass Du auch eine Wortuhr bastelst, die sind schon sehr cool :-).

Eine Organisation ist bei Github nicht viel anders als ein normaler Account. Die Organisation kann genauso Repositories haben wie ein normaler Account. Aber statt eben nur einem Benutzer zu gehören, kann man einstellen wer alles darauf zugreifen kann und was diese Benutzer dürfen.
Das hat den Vorteil, das die Repositories nicht mehr an bestimmte Leute gebunden sind, und die Entwicklung an der gleichen Stelle weiter geführt werden kann, auch wenn sich die Leute ändern.

Der Name `Wortuhr` ist denk ich schon besser als Name für eine Organisation geeignet. Du selber bist ja schließlich keine sondern baust nur eine. Also besser einen Accountnamen wählen, der Dich repräsentiert ;-)
Du kannst übrigens auch Deinen Usernamen ändern (Profilbild -> Settings -> Account -> Change Username). Dann könnte ich die Organisation anlegen und alle hier mit hinzufügen.
Wenn jemand einen anderen guten Namen für die Organisation findet, bin ich auch dabei :-)

Mein Vorschlag wäre, dass wir ein Repository für die Software Entwicklung anlegen, aber keinen direkten push dorthin erlauben, sondern nur pull-request mit automatischem Test und mit Code-Review.
Ich würde auch gerne mit einem neuen Repository anfangen um die alte History mit den eingebunden Binaries los zu werden. Wir sollten lieber GitHub Releases verwenden um die Binaries zu speichern. Die alte History können wir in ein Archiv Repository packen, damit das nicht verloren geht.

Du bist natürlich herzlich eingeladen mit an der Software mitzuarbeiten!
Wie weit bist Du denn mit Deiner Wortuhr? Sag Bescheid wenn Du Hilfe benötigst!

Liebe Grüße, Martin

**Comment by dbambus** [comment]
Hallo @tali, 

mittlerweile haben sich mehr Personen gemeldet, die an dem Projekt weiterarbeiten würden, wenn das mit dem Namen Wortuhr nicht klappen sollte, dann würde ich alternativ den Namen ESPWortuhr vorschlagen. 

Mit freundlichen Grüßen
David

**Comment by tali** [comment]
Super Vorschlag!
Und wenn das doch klappt, können wir die ja auch wieder umbenennen.

**Comment by tali** [comment]
Ich habe mal @ESPWortuhr angelegt und bin dabei das mit Leben zu füllen.

**Comment by Wortuhr** [comment]
Hallo zusammen, ich brauche eine 2. Mailadresse oder Benutzer, den ich als 2.Verwalter angeben muss.
Dann mache ich aus Wortuhr eine Org.
Gruss Markus

**Comment by tali** [comment]
@Wortuhr : brauchst du nicht!
Du kannst Deine Mailadresse beibehalten und einfach Deinen Github Benutzernamen ändern.
Ich habe inzwischen eine neue Organisation angelegt (@ESPWortuhr).
Wir könnten es also auch einfach so lassen. Aber wenn du magst, dann kannst Du Dir einen Namen aussuchen der besser zu Dir passt, und wir könnten die Organisation danach umbenennen.
Wobei mir der von @dbambus vorgeschlagene Name inzwischen auch echt gut gefällt.
